### ISSUE TITLE
Not running on device RK95 at all

### ISSUE THREAD

**Issue by HelgiBergmann** [mribbons/react-native-cipherlab-scanner#4]
I was hoped you are my week saver=) but something went wrong=)
![image](https://user-images.githubusercontent.com/78436722/138062454-b34219f8-567d-4a66-904c-9264f9b9a975.png)

**Comment by mribbons** [comment]
RK95?

Can you post a sample project and steps to reproduce the error please.

**Comment by HelgiBergmann** [comment]
https://github.com/HelgiBergmann/chiaper-lab-react-native  here repo what I try to run on the device
Then try to mess with xamarin but got some problem with broadcast and intent)
So I  decided to go to android studio to make things clear.
And...finally, I chose xamarin=)

**Comment by mribbons** [comment]
Thanks for posting the repo @HelgiBergmann.

1. You still haven't told me the steps to reproduce the error. Are you trying to build the app, are you trying to run it, do you get as far as tapping the scan button?

Can also you kindly provide:

2. The logcat which includes the crash, you should see some kind of exception related information. I would like the see the full stack trace.
`
adb shell logcat > log.txt
`
Please paste output directly or using Markdown styling. Do not attach screen shots.

3. The filename of your barcode BarcodeAPI*.jar file - This tells us the version number supported by your device.

**Comment by mribbons** [comment]
@HelgiBergmann By the way, this library won't work with Xamarin. I believe Cipherlab provides a Xamarin compatible library.

**Comment by HelgiBergmann** [comment]
@mribbons Yes, they are, so thanks for your response but I have chosed another path=)
